/**
*   @file    Os.h
*   @version 1.0.1
*
*   @brief   AUTOSAR OS - Brief file description (one line).
*   @details Detailed file description (can be multiple lines).
*
*   @addtogroup [OS]
*   @{
*/
/*==================================================================================================
*   Project              : AUTOSAR 4.2 MCAL
*   Platform             : ARM
*   Peripheral           : generic
*   Dependencies         : 
*
*   Autosar Version      : 4.2.2
*   Autosar Revision     : ASR_REL_4_2_REV_0002
*   Autosar Conf.Variant :
*   SW Version           : 1.0.1
*   Build Version        : S32K14x_MCAL_1_0_1_RTM_ASR_REL_4_2_REV_0002_20180713
*
*   (c) Copyright 2006-2016 Freescale Semiconductor, Inc. 
*       Copyright 2017-2018 NXP
*   All Rights Reserved.
==================================================================================================*/

/*==================================================================================================
==================================================================================================*/

#ifndef OS_H
#define OS_H


#ifdef __cplusplus
extern "C"
{
#endif


#include    "Os_version.h"    /**< OS version info */
#include    "Std_Types.h"     /**< Standard type header - from MCAL  */
#include    "Os_types_public.h"   /**< Autosar OS public types  */
#include    "Os_counter_api.h"

#include    "Os_cfg.h"    /* OS Configuration (generated by SysGen) */

#ifdef __cplusplus
}
#endif



#endif /*OS_H*/

/** @} */

